package com.example.search.policysearchportalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-14T11:48:31.497+05:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://example.com/search/policySearchPortalAPI", name = "policySearchPortalAPIPortType")
@XmlSeeAlso({com.guidewire.ws.soapheaders.ObjectFactory.class, com.example.search.ObjectFactory.class, ObjectFactory.class})
public interface PolicySearchPortalAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfo")
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    public com.example.search.AccountInfo getAccountInfo(

        @WebParam(name = "accountNumber", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String accountNumber
    ) throws WsiAuthenticationException_Exception;
}
