package com.example.search.policysearchportalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Mon Apr 27 13:46:59 IST 2020
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://example.com/search/policySearchPortalAPI", name = "policySearchPortalAPIPortType")
@XmlSeeAlso({com.guidewire.ws.soapheaders.ObjectFactory.class, ObjectFactory.class, com.example.search.ObjectFactory.class})
public interface PolicySearchPortalAPIPortType {

    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfo")
    @WebMethod
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfoResponse")
    public com.example.search.AccountInfo getAccountInfo(
        @WebParam(name = "accountNumber", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String accountNumber
    ) throws WsiAuthenticationException_Exception;

    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    @RequestWrapper(localName = "getPolicyInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPolicyInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfoResponse")
    public com.example.search.PolicyInfo getPolicyInfo(
        @WebParam(name = "policyNumber", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String policyNumber
    ) throws WsiAuthenticationException_Exception;
}
