package com.example.search.policysearchportalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Tue May 12 17:36:40 IST 2020
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://example.com/search/PolicySearchPortalAPI", name = "PolicySearchPortalAPIPortType")
@XmlSeeAlso({com.guidewire.ws.soapheaders.ObjectFactory.class, ObjectFactory.class, com.example.search.ObjectFactory.class})
public interface PolicySearchPortalAPIPortType {

    @WebResult(name = "return", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfo")
    @WebMethod
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfoResponse")
    public com.example.search.AccountInfo getAccountInfo(
        @WebParam(name = "accountNumber", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
        java.lang.String accountNumber
    ) throws WsiAuthenticationException_Exception;

    @WebResult(name = "return", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
    @RequestWrapper(localName = "getPolicyInfo", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPolicyInfoResponse", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfoResponse")
    public com.example.search.PolicyInfo getPolicyInfo(
        @WebParam(name = "policyNumber", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
        java.lang.String policyNumber
    ) throws WsiAuthenticationException_Exception;

    @WebResult(name = "return", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
    @RequestWrapper(localName = "getContactInfo", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetContactInfo")
    @WebMethod
    @ResponseWrapper(localName = "getContactInfoResponse", targetNamespace = "http://example.com/search/PolicySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetContactInfoResponse")
    public com.example.search.ContactInfo getContactInfo(
        @WebParam(name = "publicId", targetNamespace = "http://example.com/search/PolicySearchPortalAPI")
        java.lang.String publicId
    ) throws WsiAuthenticationException_Exception;
}
