
package com.example.search.policysearchportalapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Fri May 08 11:19:40 IST 2020
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "WsiAuthenticationException", targetNamespace = "http://example.com/search/policySearchPortalAPI")
public class WsiAuthenticationException_Exception extends Exception {
    public static final long serialVersionUID = 20200508111940L;
    
    private com.example.search.policysearchportalapi.WsiAuthenticationException wsiAuthenticationException;

    public WsiAuthenticationException_Exception() {
        super();
    }
    
    public WsiAuthenticationException_Exception(String message) {
        super(message);
    }
    
    public WsiAuthenticationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WsiAuthenticationException_Exception(String message, com.example.search.policysearchportalapi.WsiAuthenticationException wsiAuthenticationException) {
        super(message);
        this.wsiAuthenticationException = wsiAuthenticationException;
    }

    public WsiAuthenticationException_Exception(String message, com.example.search.policysearchportalapi.WsiAuthenticationException wsiAuthenticationException, Throwable cause) {
        super(message, cause);
        this.wsiAuthenticationException = wsiAuthenticationException;
    }

    public com.example.search.policysearchportalapi.WsiAuthenticationException getFaultInfo() {
        return this.wsiAuthenticationException;
    }
}
