package com.example.search.policysearchportalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-05-07T18:28:52.800+05:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://example.com/search/policySearchPortalAPI", name = "policySearchPortalAPIPortType")
@XmlSeeAlso({com.guidewire.ws.soapheaders.ObjectFactory.class, com.example.search.ObjectFactory.class, ObjectFactory.class})
public interface PolicySearchPortalAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "getPolicyInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfo")
    @ResponseWrapper(localName = "getPolicyInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetPolicyInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    public com.example.search.PolicyInfo getPolicyInfo(

        @WebParam(name = "policyNumber", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String policyNumber
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getContactInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetContactInfo")
    @ResponseWrapper(localName = "getContactInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetContactInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    public com.example.search.ContactInfo getContactInfo(

        @WebParam(name = "publicId", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String publicId
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfo")
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "http://example.com/search/policySearchPortalAPI", className = "com.example.search.policysearchportalapi.GetAccountInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://example.com/search/policySearchPortalAPI")
    public com.example.search.AccountInfo getAccountInfo(

        @WebParam(name = "accountNumber", targetNamespace = "http://example.com/search/policySearchPortalAPI")
        java.lang.String accountNumber
    ) throws WsiAuthenticationException_Exception;
}
